Repository monero-project/monero-site, pull requests merged in 2021-03, with the labels that each got.

#1492 Add Norwegian User Guides (1/2)
  _i18n/nb-no/resources/user-guides/multisig-messaging-system.md
Labels: i18n

#1493 Add Norwegian User Guides (2/2)
  _i18n/nb-no/resources/user-guides/Offline_Backup.md
  _i18n/nb-no/resources/user-guides/cli_wallet_daemon_isolation_qubes_whonix.md
  _i18n/nb-no/resources/user-guides/howto_fix_stuck_funds.md
  _i18n/nb-no/resources/user-guides/importing_blockchain.md
  _i18n/nb-no/resources/user-guides/ledger-wallet-cli.md
  _i18n/nb-no/resources/user-guides/mine-to-pool.md
  _i18n/nb-no/resources/user-guides/monero-wallet-cli.md
  _i18n/nb-no/resources/user-guides/monero_tools.md
  _i18n/nb-no/resources/user-guides/node-i2p-zero.md
  _i18n/nb-no/resources/user-guides/prove-payment.md
  _i18n/nb-no/resources/user-guides/remote_node_gui.md
  _i18n/nb-no/resources/user-guides/restore_account.md
  _i18n/nb-no/resources/user-guides/restore_from_keys.md
  _i18n/nb-no/resources/user-guides/securely_purchase.md
  _i18n/nb-no/resources/user-guides/solo_mine_GUI.md
  _i18n/nb-no/resources/user-guides/tor_wallet.md
  _i18n/nb-no/resources/user-guides/verification-allos-advanced.md
  _i18n/nb-no/resources/user-guides/verification-windows-beginner.md
  _i18n/nb-no/resources/user-guides/view_only.md
  _i18n/nb-no/resources/user-guides/vps_run_node.md
Labels: i18n

#1495 footer: fixed typo
  _includes/footer.html
Labels: grammar/typo

#1466 Translations from Weblate
  _i18n/ar.yml
  _i18n/de.yml
  _i18n/el.yml
  _i18n/es.yml
  _i18n/fr.yml
  _i18n/it.yml
  _i18n/ja.yml
  _i18n/nb_NO.yml
  _i18n/nl.yml
  _i18n/pl.yml
  _i18n/pt-br.yml
  _i18n/ru.yml
  _i18n/sr.yml
  _i18n/tr.yml
  _i18n/vi.yml
  _i18n/zh-cn.yml
  _i18n/zh-cn/resources/moneropedia/base32-address.md
  _i18n/zh-cn/resources/moneropedia/base64-address.md
  _i18n/zh-cn/resources/moneropedia/data-directory.md
  _i18n/zh-cn/resources/moneropedia/lease-set.md
  _i18n/zh-tw.yml
Labels: 🔔 Priority 🔔

#1506 what is monero: add action buttons and remove redundant header
  _i18n/en.yml
  get-started/what-is-monero/index.md
Labels: needs review
